[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++20
    -I../../../src
    -I../../../../EDP-Persistence/src
    -I../../../../EDP-System/src
